'use client';
import {useEffect,useState} from 'react'; import {supabase} from '../lib/supabase';
type Contract={id:string;name:string;ticker:string}; type Order={id:string;contract_id:string;side:'buy'|'sell';price_cents:number;remaining:number};
export default function Home(){const [user,setUser]=useState<any>(null),[league,setLeague]=useState<any>(null),[contracts,setContracts]=useState<Contract[]>([]),[orders,setOrders]=useState<Order[]>([]),[code,setCode]=useState(''),[name,setName]=useState('Fantasy 2026'),[teams,setTeams]=useState('Matthew, Max, Aarush, Karthik, Ashil'),[err,setErr]=useState('');
async function refresh(lid?:string){if(!lid)return;let {data:l}=await supabase.from('leagues').select('*').eq('id',lid).single();setLeague(l);let {data:c}=await supabase.from('contracts').select('*').eq('league_id',lid);setContracts(c||[]);let {data:o}=await supabase.from('orders').select('*').eq('league_id',lid).in('status',['open','partially_filled']);setOrders(o||[])}
useEffect(()=>{supabase.auth.getSession().then(({data})=>setUser(data.session?.user||null));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null));return()=>data.subscription.unsubscribe()},[]);
useEffect(()=>{if(!league)return;const ch=supabase.channel('market').on('postgres_changes',{event:'*',schema:'public',table:'orders',filter:`league_id=eq.${league.id}`},()=>refresh(league.id)).on('postgres_changes',{event:'*',schema:'public',table:'trades',filter:`league_id=eq.${league.id}`},()=>refresh(league.id)).subscribe();return()=>{supabase.removeChannel(ch)}},[league?.id]);
async function login(){setErr('');let {error}=await supabase.auth.signInAnonymously({options:{data:{display_name:'Trader'}}});if(error)setErr(error.message)}
async function create(){let a=teams.split(',').map(x=>x.trim()).filter(Boolean);let {data,error}=await supabase.rpc('create_demo_league',{p_name:name,p_teams:a});if(error)return setErr(error.message);setCode(data.invite_code);refresh(data.league_id)}
async function join(){let {data,error}=await supabase.rpc('join_league',{p_invite_code:code});if(error)return setErr(error.message);refresh(data.league_id)}
async function order(cid:string,side:'buy'|'sell'){let p=Number(prompt('Limit price in cents (1-99)','25')),q=Number(prompt('Lots','100'));if(!p||!q)return;let {error}=await supabase.rpc('place_order',{p_contract:cid,p_side:side,p_price:p,p_quantity:q});if(error)setErr(error.message);else refresh(league.id)}
if(!user)return <main className="center"><div className="hero"><div className="logo">FM</div><h1>Fantasy Market</h1><p>Trade your league. Win fake money. Earn real bragging rights.</p><button onClick={login}>Enter market</button><small>Play money only · no deposits or payouts</small>{err&&<b>{err}</b>}</div></main>;
if(!league)return <main><header><b>FANTASY MARKET</b><span>$10,000 starting cash</span></header><section className="panel"><h1>Start Fantasy 2026</h1><label>League name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Teams / owners<input value={teams} onChange={e=>setTeams(e.target.value)}/></label><button onClick={create}>Create market</button><div className="or">or join a friend's market</div><div className="row"><input placeholder="INVITE CODE" value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/><button onClick={join}>Join</button></div>{err&&<b>{err}</b>}</section></main>;
return <main><header><div><b>{league.name}</b><small> LIVE</small></div><span>Invite: <strong>{league.invite_code}</strong></span></header><section><h2>Championship contracts</h2><p className="muted">Price = market-implied chance. Contracts settle at $1 for the winner.</p>{contracts.map(c=>{let bid=Math.max(0,...orders.filter(o=>o.contract_id===c.id&&o.side==='buy').map(o=>o.price_cents));let asks=orders.filter(o=>o.contract_id===c.id&&o.side==='sell').map(o=>o.price_cents);let ask=asks.length?Math.min(...asks):0;return <article key={c.id}><div><strong>{c.name}</strong><small>{c.ticker}</small></div><div className="quote"><span>{bid?bid+'¢':'—'}<small>BID</small></span><span>{ask?ask+'¢':'—'}<small>ASK</small></span></div><div className="actions"><button onClick={()=>order(c.id,'buy')}>BUY</button><button className="sell" onClick={()=>order(c.id,'sell')}>SELL</button></div></article>})}</section>{err&&<div className="error">{err}</div>}<nav><span>Market</span><span>Portfolio</span><span>Leaderboard</span></nav></main>}
